Association menus with restaurants, restrict menu creation to owners who have already set up their restaurant
CraftAcademy/sf-online-august pull request #37
Opened 2016-10-04 18:12 UTC by AmberWilkie

PT Story: https://www.pivotaltracker.com/story/show/131542173

Changes proposed in this pull request:
- Create belongs_to association restaurant to menu and has_many association menus to restaurant
- Restrict menu and dish creation to owners who have set up their restaurant
- Adjust almost all the cucumber tests to account for the new restriction on menu and dish creation

What I have learned working on this feature: Big takeaway from this feature for me is shifting from terminal to browser to allow two different systems to throw errors at me. Browser gave a much more helpful presentation of the same error (subsequently fixed, of course).

Ready for review!

2016-10-04 20:33 UTC, tochman requested changes
Can't do a full review tonight but made 3 comments so far.

2016-10-04 20:33 UTC, tochman commented on app/controllers/dishes_controller.rb
> +    if current_user && current_user.role == 'owner' && !current_user.restaurant.nil?
This can be partially handled by CanCanCan

2016-10-04 20:33 UTC, tochman commented on app/controllers/menus_controller.rb
> +    if current_user && current_user.role == 'owner' && !current_user.restaurant.nil?
Same here. CanCanCan can be used for some of this functionality, like `current_user.role == 'owner'`
Also, we do have `current_user.owner?` method that could be used here.

2016-10-04 20:33 UTC, tochman commented on app/controllers/menus_controller.rb
> +    @menu = Menu.new(menu_params.merge({restaurant: restaurant}))
Here we prefer to use `restaurant.menues.create(menu_params)`

2016-10-05 05:51 UTC, AmberWilkie commented on app/controllers/dishes_controller.rb
> +    if current_user && current_user.role == 'owner' && !current_user.restaurant.nil?
done

2016-10-05 05:51 UTC, AmberWilkie commented on app/controllers/menus_controller.rb
> +    if current_user && current_user.role == 'owner' && !current_user.restaurant.nil?
done

2016-10-05 05:52 UTC, AmberWilkie commented on app/controllers/menus_controller.rb
> +    @menu = Menu.new(menu_params.merge({restaurant: restaurant}))
ok. Not stuck in my brain quite yet but getting there.

2016-10-05 07:45 UTC, tochman commented on app/controllers/dishes_controller.rb
> +    if (can? :manage, Dish) && Restaurant.exists?(user: current_user)
I would like us to visit this line together. Not sure about `Restaurant.exists?(user: current_user)`

2016-10-05 08:31 UTC, AmberWilkie commented on app/controllers/dishes_controller.rb
> +    if (can? :manage, Dish) && Restaurant.exists?(user: current_user)
We discussed. It's now extracted to application controller.

2016-10-05 08:48 UTC, tochman approved these changes

2016-10-05 08:55 UTC, merged