Remove 'add to cart' button for logged-in restaurant owners
CraftAcademy/sf-online-august pull request #39
Opened 2016-10-04 19:18 UTC by AmberWilkie

PT Story: https://www.pivotaltracker.com/story/show/131445807

Changes proposed in this pull request:
- Logged in restaurant owners cannot see add to cart button (they're not allowed to have a shopping cart - so it throws an error)

What I have learned working on this feature: I probably hadn't used an "unless" statement before, actually.

Ready for review @tochman !

2016-10-04 20:34 UTC, tochman requested changes

2016-10-04 20:34 UTC, tochman commented on app/views/dishes/show.html.haml
> +- unless !current_user.nil? && current_user.role == 'owner'
Use `current_user.owner?`

2016-10-04 20:44 UTC, AmberWilkie commented on app/views/dishes/show.html.haml
> +- unless !current_user.nil? && current_user.role == 'owner'
yes makes sense. refactored.

2016-10-04 20:46 UTC, tochman commented on app/views/dishes/show.html.haml
> +- unless !current_user.nil? && current_user.role == 'owner'
Or
If current_user && current_user.custoner?

2016-10-04 20:46 UTC, tochman commented on app/views/dishes/show.html.haml
> +- unless !current_user.nil? && current_user.role == 'owner'
Or use an ability;-)

2016-10-04 20:47 UTC, AmberWilkie commented on app/views/dishes/show.html.haml
> +- unless !current_user.nil? && current_user.role == 'owner'
Nah cuz visitors can add things to their cart. Will have to make it `current_user.owner? || current_user.admin?` when we get around to adding admins, but everybody else should see that button

2016-10-05 04:57 UTC, tochman commented on app/views/dishes/show.html.haml
> +- unless !current_user.nil? && current_user.role == 'owner'
I don't agree ;-) Pushed up a commit that uses ability (we can revert if that is not a solution you approve)

2016-10-05 05:00 UTC, tochman approved these changes

2016-10-05 05:27 UTC, AmberWilkie commented
Ok I dig it. I guess I was thinking about authorization the wrong way.

2016-10-05 05:35 UTC, tochman commented
Cool

2016-10-05 05:35 UTC, merged