H1 partials (design)
CraftAcademy/sf-online-august pull request #50
Opened 2016-10-06 14:14 UTC by thesuss

PT Story: [paste pivotal tracker link here]

Changes proposed in this pull request:
- Partial with header h1 and static background image 

What I have learned working on this feature: 
- Sending a variable from haml page to partial - or there setting a default one
 
Screenshots: 
<img width="898" alt="skarmavbild 2016-10-06 kl 16 11 20" src="https://cloud.githubusercontent.com/assets/7266909/19155763/f23fd220-8bdf-11e6-908d-1db0fec69c8e.png">

Ready for review!

2016-10-06 14:18 UTC, tochman commented on app/views/carts/index.html.haml
> +  - @headline = "Your cart"
This is great but should be set in a helper. Not in views

2016-10-06 14:19 UTC, tochman commented on app/views/carts/checkout.html.haml
> +- @headline = "Hey #{current_user.name}, you're checking out"
Avoid this kind of assignment in the view. We have helpers for that.

2016-10-06 14:30 UTC, thesuss commented on app/views/carts/checkout.html.haml
> +- @headline = "Hey #{current_user.name}, you're checking out"
Okay, will see if I can research that.

2016-10-06 14:43 UTC, thesuss commented on app/views/carts/checkout.html.haml
> +- @headline = "Hey #{current_user.name}, you're checking out"
Or do you mean to do it in the controllers instead?

2016-10-06 15:22 UTC, thesuss commented on app/views/carts/checkout.html.haml
> +- @headline = "Hey #{current_user.name}, you're checking out"
I moved most to controller (couldnt with the devise pages?), and will research how to do what I want with a helper method.

2016-10-06 15:30 UTC, thesuss commented on app/views/carts/checkout.html.haml
> +- @headline = "Hey #{current_user.name}, you're checking out"
And tha works for some views, but not for all...

2016-10-06 19:43 UTC, diraulo commented
@tochman This one is red due to minor coverage drop.
@thesuss You have a merge conflict to take care of here

2016-10-06 19:47 UTC, tochman commented
I can't see the coverage for some reason but I would like to see what lines in the menus_controller are not covered. It's usually a sad path issue. We might as well try to test every line @diraulo

2016-10-06 19:54 UTC, diraulo commented on app/controllers/menus_controller.rb
> +    @headline = "All menues"
This should be `All menus`

2016-10-06 19:57 UTC, tochman commented on app/views/menus/show.html.haml
> +    - if current_user == @menu.restaurant.user #this is throwing a nil error
Probably out of scope but this should be handled by an ability
```
- if can? :manage, menu
```

2016-10-07 06:50 UTC, tochman commented
You are still usuig double quotes @thesuss I will work on this for a while now so pleas do not alter your code.

2016-10-07 13:41 UTC, tochman requested changes

2016-10-07 13:41 UTC, tochman commented on app/controllers/carts_controller.rb
> +  end
Why is this added back in?

2016-10-07 13:41 UTC, tochman commented on app/controllers/dishes_controller.rb
> +    @dish = Dish.find(params[:id])
There is a `before_action` that sets the dish already.

2016-10-07 13:41 UTC, tochman commented on app/views/carts/checkout.html.haml
> +  %h1 = "Hey #{current_user.name}, you're checking out"
Is this view displayed AFTER processing of payment? If so we probably want to say "You have checked out" or something...

2016-10-07 13:41 UTC, tochman commented on features/cart_page.feature
> +    Given I am not logged in
Why do we care if the user is logged in or not in this scenario?

2016-10-07 13:41 UTC, tochman commented on features/edit_dish.feature
> +    Then I should not see "Edit dish"
So the conditional display of the Edit button is one thing but I would also like to see a test for what is happening when a user tries to access the route for a dish that is not his own directly.

2016-10-07 13:41 UTC, tochman commented on app/views/devise/passwords/edit.html.haml
> +              (#{@minimum_password_length} characters minimum)
Hmm... Are we using `@minimum_password_length` in this app? Can't remember any scenario for that.

2016-10-07 13:48 UTC, thesuss commented on app/controllers/carts_controller.rb
> +  end
I don't know? 
Perhaps I didnt spot it in a merge conflict

2016-10-07 13:50 UTC, thesuss commented on app/views/carts/checkout.html.haml
> +  %h1 = "Hey #{current_user.name}, you're checking out"
It is where the button to stripe will be

2016-10-07 13:50 UTC, thesuss commented on features/cart_page.feature
> +    Given I am not logged in
If you are logged in as owner you can not see the add to cart button.

2016-10-07 13:51 UTC, thesuss commented on features/edit_dish.feature
> +    Then I should not see "Edit dish"
That will happen/is happening in my other pr

2016-10-07 13:52 UTC, thesuss commented on app/views/devise/passwords/edit.html.haml
> +              (#{@minimum_password_length} characters minimum)
It is set by default in devise, we could add tests for that but we haven't prioritized it.

2016-10-07 16:07 UTC, tochman commented on app/views/devise/passwords/edit.html.haml
> +              (#{@minimum_password_length} characters minimum)
I see no need to add this to the view if that functionality is not activated

2016-10-07 16:08 UTC, tochman commented on app/views/devise/passwords/edit.html.haml
> +              (#{@minimum_password_length} characters minimum)
It's not a blocker though

2016-10-07 16:10 UTC, tochman commented
But there are merge conflicts :-(

2016-10-07 18:22 UTC, thesuss commented
Fixed them, running rake

2016-10-07 18:24 UTC, tochman commented on app/views/carts/checkout.html.haml
> +  %h1 = "Hey #{current_user.name}, you're checking out"
Hmm... no, that button is placed on ` carts/index.html.haml`
```
      - if current_user
        = form_tag charges_path do
          = hidden_field_tag :cart_id, @cart.id
          %script.stripe-button{ src: 'https://checkout.stripe.com/checkout.js',
              data: {amount: @cart.total*100, description: 'Whatever', key: ENV['STRIPE_PUBLISHABLE_KEY'], currency: 'sek'}}
```

2016-10-07 18:27 UTC, tochman commented on features/cart_page.feature
> +    Given I am not logged in
My objection to you using this step in this particular scenario is that we don't log in a user in the background. So there is no user logged in no matter what, right?

2016-10-07 18:29 UTC, tochman commented on features/edit_dish.feature
> +    Then I should not see "Edit dish"
If it was already part of the codebase I see no reason to remove it or add it in another PR where it will probably be out of scope (also that particular pr is already growing out of proportion)

2016-10-07 18:32 UTC, thesuss commented on features/cart_page.feature
> +    Given I am not logged in
I see that now, I will pry to see why it fails without that line.

2016-10-07 18:41 UTC, thesuss commented on features/edit_dish.feature
> +    Then I should not see "Edit dish"
Okay. I'll add it again.

2016-10-07 19:50 UTC, tochman requested changes

2016-10-07 19:50 UTC, tochman commented on app/controllers/application_controller.rb
> +
Sorry, but this is supposed to be handled by a CanCanCan ability

2016-10-07 19:50 UTC, tochman commented on app/controllers/dishes_controller.rb
> +  before_action :owner_of_restaurant?, only: :edit
`load_and_authorize_resource` takes care of that authorization

2016-10-07 19:54 UTC, tochman requested changes

2016-10-07 19:54 UTC, tochman commented on app/views/dishes/show.html.haml
> +      - if (can? :manage, Dish) && (current_user == @dish.restaurant.user)
`can? :manage, Dish` should be enough, depending on how that ability is configured. Have a look at that before adding conditions

2016-10-07 19:54 UTC, tochman commented on app/views/menus/show.html.haml
> +      - if (can? :manage, Menu) && (current_user = @menu.restaurant.user)
Same here, if the ability is set up correctly, `can? :manage, Menu` should be enough to prevent unauthorized access.

2016-10-07 19:54 UTC, tochman commented on app/views/restaurants/show.html.haml
> +      - if (can? :manage, Restaurant) && (current_user == @restaurant.user)
Same here.

2016-10-07 20:00 UTC, tochman commented
I understand that there are lot of comments from my side but this PR is way out of scope. From dealing with headers on each page we are now facing a situation where we are modifying authorization rules. There are lot of benefits from following the process of small, well scoped features - avoiding situations like this one is just one of them. I'm not going to make to big deal out of this but I want the entire team to understand that reviewing this kind of PR's is extremely hard and takes up a lot of the coaches time and energy. Let's take a moment and reflect on the process and how we can avoid this kind of situations.

2016-10-07 20:08 UTC, thesuss commented
I agree, thats why I wanted to do this in the other PR, or a separate one alltogether.

2016-10-07 20:09 UTC, tochman commented
In that case none of this steps should have been altred to start with.

2016-10-07 20:12 UTC, closed without merging