Menu view
CraftAcademy/sf-online-august pull request #6
Opened 2016-09-27 16:11 UTC by JesperGreen

PT Story: https://www.pivotaltracker.com/story/show/131070515

Changes proposed in this pull request:
Added a link on the restaurant page to menu.
Added menu view/controller/routes

What I have learned working on this feature: learned to get path's with helper methods

Screenshots: 
<img width="654" alt="screen shot 2016-09-27 at 6 03 03 pm" src="https://cloud.githubusercontent.com/assets/19630111/18881704/b0451c5e-84dc-11e6-860b-c5e9c48a3437.png">

<img width="327" alt="screen shot 2016-09-27 at 6 03 37 pm" src="https://cloud.githubusercontent.com/assets/19630111/18881718/c0cdfa14-84dc-11e6-937b-83cc8f3be48a.png">

Ready for review!

2016-09-27 16:44 UTC, tochman requested changes
Please review comments

2016-09-27 16:44 UTC, tochman commented on app/views/menu/index.html.erb
> +</div>
I would really prefer if you guys made a switch to HAML.

2016-09-27 16:44 UTC, tochman commented on features/step_definitions/basic_steps.rb
> +  @goto = '/menu'if page == "menu"
Please use a `case` statement here

2016-09-27 16:44 UTC, tochman commented on features/step_definitions/basic_steps.rb
> +  @goto = '/menu'if page == "menu"
Also there is no need to use an instance variable, just return a value.

2016-09-27 16:47 UTC, tochman commented
Okay, so for some reason you guys keep having the original pr from @AmberWilkie as the first commit in ALL PR's. With consequential merge conflicts. Please fix that. Make sure you all delete your local `develop` branches and checkout `upstream/develop`
```
$ git checkout -t upstream/develop` 
```

2016-09-28 09:48 UTC, JesperGreen commented on app/views/menu/index.html.erb
> +</div>
Done

2016-09-28 09:48 UTC, JesperGreen commented on features/step_definitions/basic_steps.rb
> +  @goto = '/menu'if page == "menu"
And Done.
Thanks.

2016-09-28 10:18 UTC, tochman commented
- I would like you to spend a few minutes and reflect on what you learned while working on this PR. Is it really just the helper methods?
- I would also argue that the HAML translation should have been done in a separate PR with it's own chore in the Tracker. 
- Also, please make use past sentence and bullet points when listing proposed changes (read up on markdown)

**This is not a blocker though so I'll go ahead and merge this. I will look for an updated PR description anyway.**

2016-09-28 10:19 UTC, tochman approved these changes

2016-09-28 10:19 UTC, merged

2016-09-28 10:30 UTC, tochman commented
Much better description. Thank you.