Add highlighted dishes to Restaurant show page
CraftAcademy/sf-online-august pull request #63
Opened 2016-10-08 09:34 UTC by AmberWilkie

PT Story: https://www.pivotaltracker.com/story/show/131070359

Changes proposed in this pull request:
- Creates `highlight` boolean for dishes
- Puts highlight checkbox on dish edit and create pages
- Displays highlighted dishes (max six) on restaurant show pages
- Updates seed to randomly highlight some dishes

What I have learned working on this feature:
- I'm super-crap at design.

Screenshots: 
![screen shot 2016-10-08 at 11 34 05 am](https://cloud.githubusercontent.com/assets/20141428/19212121/3baf94e2-8d4b-11e6-96e8-33172f977972.png)

Ready for review!

2016-10-08 11:15 UTC, thesuss reviewed
Why did you move it? Was it in the scope of this feature? :)

2016-10-08 19:26 UTC, tochman commented on db/seeds.rb
> +              restaurant_id: restaurant.id,
`restaurant: restaurant` should do. ActiveRecord magic ;-)

2016-10-08 19:27 UTC, tochman commented on features/highlight_dish.feature
> +  When I am on my restaurant page
Shouldn't this be `Then I should be on my restaurant page` ?  It doesn't really make sense the way it is now.

2016-10-08 19:27 UTC, tochman commented on features/highlight_dish.feature
> +  When I am on my restaurant page
Same here...

2016-10-08 19:28 UTC, tochman commented on features/step_definitions/restaurant_steps.rb
> +  expect(dish.highlight).to eq true
Please don't add assertions in steps that are setting the stage for the test ('Given' steps)

2016-10-09 08:47 UTC, AmberWilkie commented
@thesuss I moved it the `_form` partial because I was the one who had moved it to `application` in the first place and it doesn't belong there, according to the pattern of the other folders. But if it has to stay there to be convenient for you, it's zero problem. When I pull upstream right now I'll just keep whatever you have.

2016-10-09 08:47 UTC, AmberWilkie commented on features/step_definitions/restaurant_steps.rb
> +  expect(dish.highlight).to eq true
Right, yes, my bad. I should have taken that out after it worked the first time.

2016-10-09 08:48 UTC, AmberWilkie commented on features/highlight_dish.feature
> +  When I am on my restaurant page
Well here it's ok, right? Viewing your restaurant page when not logged in? I was just trying to use steps we already had written.

2016-10-09 08:49 UTC, tochman commented on features/highlight_dish.feature
> +  When I am on my restaurant page
Okay, but it should say `And`

2016-10-09 08:50 UTC, tochman commented
Rounded corners is sooo 2013! ;-)

2016-10-09 08:54 UTC, thesuss commented
It is. But 2014 ;-)

2016-10-09 08:56 UTC, AmberWilkie commented
I gave it a try but obviously I'm not very good at this stuff. Hoping one of the front-enders will rescue me from myself.

2016-10-09 08:56 UTC, AmberWilkie commented on db/seeds.rb
> +              restaurant_id: restaurant.id,
done

2016-10-09 08:57 UTC, AmberWilkie commented on features/highlight_dish.feature
> +  When I am on my restaurant page
When
And
And
Then

2016-10-09 08:57 UTC, AmberWilkie commented on features/highlight_dish.feature
> +  When I am on my restaurant page
done

2016-10-09 09:07 UTC, tochman commented
This feels 'done' IMO. Centering the map on marker click was a suggestion but not part of this story. You have surely learned more than the insight about your design skills when working on this feature @AmberWilkie , haven't you?

2016-10-09 09:09 UTC, AmberWilkie commented
This isn't the center-map-markers one :)

2016-10-09 09:10 UTC, tochman requested changes

2016-10-09 09:10 UTC, tochman commented on app/controllers/dishes_controller.rb
> +    params.require(:dish).permit(:name, :description, :price, :allergies, :ingredients, :calories, {menu_ids: []}, :highlight)
I would add line breaks to avoid loc's longer than 80 charackters

2016-10-09 09:10 UTC, tochman commented
Wow, I'm getting confused by the amount of PRs My bad @AmberWilkie

2016-10-09 09:12 UTC, AmberWilkie commented on app/controllers/dishes_controller.rb
> +    params.require(:dish).permit(:name, :description, :price, :allergies, :ingredients, :calories, {menu_ids: []}, :highlight)
done

2016-10-09 09:13 UTC, tochman approved these changes

2016-10-09 09:18 UTC, merged