Create Dishes and display them on Dish pages
CraftAcademy/sf-online-august pull request #7
Opened 2016-09-28 14:34 UTC by AmberWilkie

PT Story: https://www.pivotaltracker.com/story/show/131070277 (and parts of https://www.pivotaltracker.com/story/show/131070519)

Changes proposed in this pull request:
Create Dish model
Route to Dish model functions: new, create, show (and others we're not using yet)
Dish views: new and show

What I have learned working on this feature: Strengthening model-controller-view understanding (just through repetition, really). We re-learned a number of features, like using flash messages with error handling. We also learned that you can sanitize parameters by explicitly declaring them, but if you want to use `params[:object]`, you need to sanitize individual key-value pairs.

Screenshots: 
![screen shot 2016-09-28 at 4 32 26 pm](https://cloud.githubusercontent.com/assets/20141428/18917839/31e242e8-8599-11e6-889d-14e16db8f369.png)
![screen shot 2016-09-28 at 4 33 05 pm](https://cloud.githubusercontent.com/assets/20141428/18917854/43a4ead0-8599-11e6-98db-5270649646cd.png)

Ready for review!

2016-09-28 14:43 UTC, tochman requested changes
I assume that the Dish model will be associated with a Menu and consequently with a Restaurant at some point, right?

2016-09-28 14:43 UTC, tochman commented on app/controllers/dishes_controller.rb
> +require 'pry'
Don't think you need to require pry here.

2016-09-28 14:43 UTC, tochman commented on config/routes.rb
> +  resources :dishes
This creates all CRUD routes. Do you use them? I would suggest that you only create the ones you actually use.

2016-09-28 14:44 UTC, tochman commented
Great test coverage 👍🏽

2016-09-28 14:45 UTC, AmberWilkie commented on app/controllers/dishes_controller.rb
> +require 'pry'
gone now

2016-09-28 14:48 UTC, AmberWilkie commented
We will eventually be associating dishes with menus but that's in a separate feature down the line (probably next up, actually).

2016-09-28 14:49 UTC, AmberWilkie commented on config/routes.rb
> +  resources :dishes
restricted to next-to-all-routes

2016-09-28 15:11 UTC, tochman requested changes

2016-09-28 15:11 UTC, tochman commented on config/routes.rb
> +  resources :dishes, only: [:new, :show, :create, :edit, :destroy]
Do you have edit and destroy actions?

2016-09-28 15:11 UTC, tochman commented on app/controllers/dishes_controller.rb
> +  def sanitized_params
I would call this dish_params

2016-09-28 15:13 UTC, tochman commented on features/step_definitions/basic_steps.rb
> -  expect(current_path).to eq expected_page
Why did you remove this definition?

2016-09-28 16:01 UTC, AmberWilkie commented on config/routes.rb
> +  resources :dishes, only: [:new, :show, :create, :edit, :destroy]
We will.

2016-09-28 16:05 UTC, AmberWilkie commented on app/controllers/dishes_controller.rb
> +  def sanitized_params
renamed

2016-09-28 16:06 UTC, AmberWilkie commented on features/step_definitions/basic_steps.rb
> -  expect(current_path).to eq expected_page
We had two. We should have removed the other one, actually. I've changed that test to match this one and everything's still running green. We just went through the merge too quickly.

2016-09-28 16:06 UTC, tochman commented on config/routes.rb
> +  resources :dishes, only: [:new, :show, :create, :edit, :destroy]
Please just create the things needed atm. Really, if you create other routes you deprive whoever will work on the next feature the joy of creating them. 😉😀

2016-09-28 16:09 UTC, tochman commented on features/step_definitions/basic_steps.rb
> -  expect(current_path).to eq expected_page
They were not the same. One navigated to a page the other asserted it was on a page.  Of course all the test go green.  If you navigate to a page and asset that you are on the page in the same definition the test will go green automatically.  I asked you not to have assertions in navigatio steps

2016-09-28 16:09 UTC, tochman commented on features/step_definitions/basic_steps.rb
> -  expect(current_path).to eq expected_page
They were not the same. One navigated to a page the other asserted it was on a page.  Of course all the test go green.  If you navigate to a page and asset that you are on the page in the same definition the test will go green automatically.  I asked you not to have assertions in navigatio steps

2016-09-28 16:12 UTC, AmberWilkie commented
WTF, Coveralls?
```
0m7.302s
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #18.1
[Coveralls] https://coveralls.io/jobs/18658143
Coverage is at 81.82%.
```

2016-09-28 16:17 UTC, AmberWilkie commented on features/step_definitions/basic_steps.rb
> -  expect(current_path).to eq expected_page
But you didn't ask us not to have expectations on navigation steps. You asked us not to have them on given steps. With the test as it is now (corrected from the code above), we are expecting to be on a page after a button is clicked. We're testing a redirect. We'll eventually have another "visit a the "blah blah blah" page" where we will actually visit the page we expect to be on

2016-09-28 16:19 UTC, tochman commented on features/step_definitions/basic_steps.rb
> -  expect(current_path).to eq expected_page
OK we can have a look at this tomorrow

2016-09-28 16:19 UTC, tochman commented on features/step_definitions/basic_steps.rb
> -  expect(current_path).to eq expected_page
OK we can have a look at this tomorrow

2016-09-29 07:36 UTC, tochman approved these changes

2016-09-29 07:36 UTC, merged

2016-09-29 11:14 UTC, tochman commented on features/dish_creation.feature
> +  Then I should see "Dish desc can't be blank"
Okay, so here's the problem that I raised with @AmberWilkie and @Blokkinen By giving the Dosh model an attribute of `dish_desc` we end up with messages like this: "Dish desc can't be blank". To me that is bad UX ;-)

2016-09-29 11:15 UTC, tochman commented on features/dish_creation.feature
> +  Then I should see "Dish price can't be blank"
Here I would also prefer "Price can't be blank" rather than "Dish price can't be blank". It's also an attribute naming issue.