Restaurant Index Api Response
CraftAcademy/sf-online-august pull request #75
Opened 2016-10-10 18:07 UTC by thesuss

PT Story: 
https://www.pivotaltracker.com/story/show/131984201

Changes proposed in this pull request:
- Add request specs for Restaurant api
- Add controller for Restaurant api
- Add jbuilder file for Restaurant index api response

What I have learned working on this feature: 
- An error in Routes can change the expected response from the application
- API:s are rather easy to create, with the tools provided

Screenshots (postman):
<img width="963" alt="skarmavbild 2016-10-10 kl 20 03 34" src="https://cloud.githubusercontent.com/assets/7266909/19246122/1913dc78-8f25-11e6-92a4-ba26fe166776.png">
 

Ready for review!

2016-10-10 20:18 UTC, tochman requested changes

2016-10-10 20:18 UTC, tochman commented on spec/requests/api/v1/restaurants_spec.rb
> +    let!(:owner_2) do
This one is never used.

2016-10-10 20:18 UTC, tochman commented on spec/requests/api/v1/restaurants_spec.rb
> +      json_response = JSON.parse(response.body)
Could be extracted to a separate method or helper since you're using this in many tests

2016-10-11 06:23 UTC, thesuss commented on spec/requests/api/v1/restaurants_spec.rb
> +    let!(:owner_2) do
Removed

2016-10-11 06:24 UTC, thesuss commented on spec/requests/api/v1/restaurants_spec.rb
> +      json_response = JSON.parse(response.body)
Done

2016-10-11 06:27 UTC, tochman commented on spec/requests/api/v1/restaurants_spec.rb
> +  let(:headers) { { HTTP_ACCEPT: 'application/json' } }
Where are you using the headers?

2016-10-11 06:27 UTC, tochman commented on spec/support/response_json.rb
> +end
I would add this config in rails_helper for better readability

2016-10-11 07:21 UTC, thesuss commented on spec/requests/api/v1/restaurants_spec.rb
> +  let(:headers) { { HTTP_ACCEPT: 'application/json' } }
removed

2016-10-11 07:21 UTC, thesuss commented on spec/support/response_json.rb
> +end
done

2016-10-11 08:55 UTC, tochman approved these changes

2016-10-11 08:55 UTC, tochman commented
So there are issues with this RP that will lead to merge conflicts in the future, but let's go with that.

2016-10-11 10:10 UTC, merged