Create an API endpoint for checking out
CraftAcademy/sf-online-august pull request #82
Opened 2016-10-14 13:45 UTC by thesuss

PT Story: 
https://www.pivotaltracker.com/story/show/132316359

Changes proposed in this pull request:
- request spec for return from API upon checkout

What I have learned working on this feature: 
- Request specs gets easier the more of them you create

Ready for review!

2016-10-14 13:48 UTC, tochman commented on spec/requests/api/v1/checkout_spec.rb
> +                                 'total'=>2})
How about we return some sort success message? And how about the `sad-path`?

2016-10-14 13:53 UTC, tochman commented on spec/requests/api/v1/checkout_spec.rb
> +  let(:dish) { create(:dish, restaurant: restaurant, name: 'Spaghetti') }
Why do we care about the name of the dish?

2016-10-14 13:54 UTC, tochman commented on app/controllers/api/v1/carts_controller.rb
> +  end
Shouldn't we assign a shopping cart to a user on checkout?

2016-10-15 19:01 UTC, tochman requested changes

2016-10-15 19:01 UTC, tochman commented on app/controllers/api/v1/carts_controller.rb
> +  end
Any action on this?

2016-10-15 19:01 UTC, tochman commented on spec/requests/api/v1/checkout_spec.rb
> +  let(:dish) { create(:dish, restaurant: restaurant, name: 'Spaghetti') }
Any action on this?

2016-10-15 19:01 UTC, tochman commented on spec/requests/api/v1/checkout_spec.rb
> +                                 'total'=>2})
Any action on this?

2016-10-16 08:18 UTC, tochman approved these changes

2016-10-16 08:23 UTC, tochman commented on app/controllers/api/v1/carts_controller.rb
> +    no_dishes_error
I wonder if you should condition this somehow? Like:
```
@cart.paid = true unless no_dishes_error
````

2016-10-16 08:25 UTC, tochman commented
Looks good. I have no real objections apart from the comment I made.

2016-10-16 08:27 UTC, AmberWilkie commented on spec/requests/api/v1/checkout_spec.rb
> +    expect(cart.paid).to eq false
So I tested the `@cart.paid == true`... if it goes into one of the error scenarios, it doesn't set the cart as paid.

2016-10-16 08:29 UTC, tochman commented on spec/requests/api/v1/checkout_spec.rb
> +    expect(cart.paid).to eq false
I understand that but it looks a bit weird in the controller method. This is not a blocker. I just note that reading this feels weird.

2016-10-16 09:02 UTC, AmberWilkie commented
Ok I changed that line as per your suggestion. Tests are fine.

2016-10-16 09:06 UTC, merged